### ISSUE TITLE
Help for dummies

### ISSUE THREAD

**Issue by gabo-di** [TeXhackse/LaTeX-ZUGFeRD#1]
Hello,

I am trying to use your package, it is literally my first time trying to use lua or lualatex. (I am not even sure that I have to use them).
But I tried the following command
```
lualatex zugferd.ins
```
this gave some output, then I tried the command
```
lualatex zugferd.dtx
```
and this one already gives me an error:
``` 
! Undefined control sequence.
l.31 \pdfmeta_xmp_xmlns_new:nn
                            {fx}{urn:factur-x:pdfa:CrossIndustryDocument:inv...
```
and if press Enter and go on I have more errors and can not generate the invoice pdf with
```
lualatex DEMO-rechnung-zugferd.tex
```
So if please you could write a readme.md for dummies it will be most appreciated.

Additional info
```
lualatex --version
This is LuaHBTeX, Version 1.16.0 (TeX Live 2023)
Development id: 7567
```

**Comment by TeXhackse** [comment]
You TeX Live is too old. As this package is using new mechanisms you need to update. I will change the version requirement to improve the visability of this fact.

**Comment by TeXhackse** [comment]
Generally we have an l3build script in there so you should be able to run it via l3build doc- 

I sadly didn't find enough free time to finish the documentation yet.

**Comment by gabo-di** [comment]
Thank you for the response and for the code.

Updating texlive did the trick, I can create the DEMO-[...].pdf, and check that is a valid zugferd file.

 Although there is still a problem with the command
```
lualatex zugferd.dtx
```
that is not an actual issue for me now.

**Comment by WolfgangRohrmoser** [comment]
some notes how it worked for me ( using Ubuntu 24.04)

$  lualatex -version
This is LuaHBTeX, Version 1.17.0 (TeX Live 2023/Debian)
Development id: 7581

# apt install texlive-lualatex texlive-latex-recommended  texlive-latex-extra texlive-science

$  l3build doc  # results are in build/doc/

# use it for other invoices
$  cp ./build/local/zugferd.sty .
$  lualatex DEMO-rechnung-zugferd.tex

this will build the PDF document + embedded XML file in current directory

thank you for your work, it saves me a lot of time..

**Comment by TeXhackse** [comment]
@WolfgangRohrmoser Out of curiosity: Does l3build install throw a warning/error on debian? That would be even more annoying than the other issues with the TeX Live package there.

**Comment by TeXhackse** [comment]
My fault  … Actually I thought I had that in the README but seems I did not…

**Comment by TeXhackse** [comment]
I added those instructions to the README and published the part I already had for the docs. will still be working on that, but am closing this issue for now, to feel a bit less demanded.

Generally I will try to help out, just have to see how much free time I can spend on this. As I expect you to write invoices yourself this is probably understandable ;-)
