### ISSUE TITLE
Feature: Add machine readable due date in `SpecifiedTradePaymentTerms`

### ISSUE THREAD

**Issue by freswa** [TeXhackse/LaTeX-ZUGFeRD#11]
The `SpecifiedTradePaymentTerms` may contain a machine readable `DueDateDateTime` with a nested `DateTimeString`. This is very useful to extract the due date automatically in accounting software. I'd propose to add a
```
payment-terms/date .str_gset:N = \__zugferd_payment_terms_date_str,
```
and add the xml fields conditionally in `\__zugferd_SpecifiedTradePaymentTerms`.

**Comment by TeXhackse** [comment]
We already have `due-date` it's jsut described with the dates as it matches that structure. I will recheck the documentation on this.

**Comment by freswa** [comment]
Well, I'll go and rtfm - sorry :/
