### ISSUE TITLE
Help wanted: minimal working example

### ISSUE THREAD

**Issue by dim13** [TeXhackse/LaTeX-ZUGFeRD#15]
I'm trying to assemble a minimal working example based on documentation and test files:

```
\DocumentMetadata{
        pdfstandard=a-3b,
        lang=de,
}
\documentclass{article}
\usepackage{zugferd}

\SetZUGFeRDData{
	seller/name = {peiTeX (Marei Peischl)},
	seller/email = {invoicing@peitex.de},
	seller/vatid = {DE123456789},
	seller/contact= {Marei\\+4900000000\\marei@peitex.de},
	seller/address = {Address Line 1\\Address Line 2},
	seller/postcode = {20253},
	seller/city ={Hamburg},
	seller/country = {DE},
}

\begin{document}
\begin{ZUGFeRD}
	\zugferd_write_Item:nnnnnn {1} {} {Plushie~\TeX\ lion} {31.98} {2} {63.78}
	\zugferd_startInvoiceSums:
	\zugferd_write_TaxEntry:nnnn {S} {19} {63.78} {12.12}
	\zugferd_write_Summation:nnnnnnnn {63.78} {0} {0} {63.78} {12.12} {75.90} {0} {75.90}
	\zugferd_stopInvoiceSums:
\end{ZUGFeRD}
\end{document}
```

However it fails with:
```
! Undefined control sequence.
<recently read> \zugferd

l.21 	\zugferd
            _write_Item:nnnnnn {1} {} {Plushie~\TeX\ lion} {31.98} {2} {63.78}
```
and any other `\zugferd_*` command.

zugferd version 0.9

lualatex version 1.18.0 (TeX Live 2024)

Not sure, what I'm doing wrong?…

**Comment by TeXhackse** [comment]
You are mixing up LaTeX2e Syntax with expl3. In case you would like to use the expl3 Syntax directly you would have to enable it. 

Thats done using `\ExplSyntaxOn` and switched off by `\ExplSyntaxOff`.

For more general introduction in expl3 you can have a look at https://tug.org/TUGboat/tb44-1/tb136peischl-expl3.html (I can add links to the German or French variant later as soon as I find time.)

**Comment by dim13** [comment]
Thanks! That helped.
