### ISSUE TITLE
DEMO-rechnung-zugferd.tex: Does not work with (outdated) TL 2024

### ISSUE THREAD

**Issue by t-b** [TeXhackse/LaTeX-ZUGFeRD#16]
TL 2024 on debian bookworm.

```
$ tlmgr info zugferd
package:     zugferd
category:    Package
shortdesc:   ZUGFeRD and Faktur-X invoicing using LaTeX
longdesc:    This package provides interfaces to allow creating ZUGFeRD or Faktur-X invoices with LaTeX including the XML file. It can be used to modify personal invoicing templates to fulfil the requirements for digital invoicing without further modification of the invoicing processes.
installed:   Yes
revision:    72638
sizes:       src: 93k, doc: 453k, run: 49k
relocatable: No
cat-version: 0.9
cat-license: lppl1.3c
cat-topics:  invoice
cat-contact-support: https://github.com/TeXhackse/LaTeX-ZUGFeRD/issues
cat-contact-repository: https://github.com/TeXhackse/LaTeX-ZUGFeRD.git
collection:  collection-latexextra
```

I'm unable to get the DEMO tex file working. I get with lualatex and pdflatex the following errors:

```
! Undefined control sequence.
<argument> ...ce:1p0\c_hash_str }\pdfmeta_xmp_schema_new:nnn 
                                                  {Factur-X PDFA Extension S...

l.128 }
     
? X
 481 words of node memory still in use:
   2 hlist, 1 rule, 1 dir, 3 kern, 1 glyph, 4 attribute, 66 glue_spec, 4 attrib
ute_list, 2 if_stack, 1 write, 2 late_lua nodes
   avail lists: 2:19,3:2,7:29,9:3,11:3

warning  (pdf backend): no pages of output.
Transcript written on DEMO-rechnung-zugferd.log.
```

[DEMO-rechnung-zugferd.log](https://github.com/user-attachments/files/17604447/DEMO-rechnung-zugferd.log)

**Comment by TeXhackse** [comment]
This is debian specific you need the most recent LaTeX release. If you installed the package via tlmgr it should be able you update your TeX Live to the current version then it should be fine.

**Comment by TeXhackse** [comment]
So to be clear: it does not work with the debian package, that's true as the macros are newer than that. But running a `tlmgr update --self --all`  should help.

**Comment by t-b** [comment]
Thanks for the prompt reply. Doing "tlmgr update --self --all" fixed the issue.

Btw. I'm not using the debian package but installed TL 2024 from the DVD image.

**Comment by TeXhackse** [comment]
I realized that, that's why i changed the heading again. Thanks for making that clear and sorry for the confusion, was a bit late ;-)

**Comment by TeXhackse** [comment]
I added an error message on this issue if the pdfmanagement is too old
