### ISSUE TITLE
\citeauthor at documentation producing empty result for CTAN

### ISSUE THREAD

**Issue by koppor** [TeXhackse/LaTeX-ZUGFeRD#23]
LaTeX seems to be right:

https://github.com/TeXhackse/LaTeX-ZUGFeRD/blob/29de490f1e9d5465fdfaa0ca9c4a59c17f7a8093/zugferd.dtx#L294

Howver, on CTAN, there is an empty space instead of an author:

![image](https://github.com/user-attachments/assets/f55c6eb3-de68-4388-9074-37c243d4387d)

**Comment by TeXhackse** [comment]
Actually it's not right, as I wanted to cite the title there not the author ;-)
