### ISSUE TITLE
XRECHNUNG profile uses wrong file name. 

### ISSUE THREAD

**Issue by u-fischer** [TeXhackse/LaTeX-ZUGFeRD#26]
According to section 7.7 Das Referenzprofil XRECHNUNG of the standard downloaded from https://www.ferd-net.de/standards/paket-downloads/index.html XRECHNUNG should use 
the file name `xrechnung.xml` and `fx:ConformanceLevel XRECHNUNG` and `fx:DocumentFileName` `xrechnung.xml.

**Comment by TeXhackse** [comment]
Thanks for reporting. Actually this is already fixed on the development branch. Missing documentation so far. 

Anyway … there is another thing I wanted to ask you anyway which is similar: Some viewers require the  name of the attachment to be the same. So they expect the filename to be the `\__pdfmanagement_EmbeddedFiles_name:` to match that. I did not find any information in the standard to match this until now.

**Comment by u-fischer** [comment]
Not quite what the question is. Naturally you have to embed your xml with this name, so 

~~~~
\pdffile_embed_file:nnn {\g__zugferd_xml_file_tl}{xrechnung.xml}
{zugferd/rechnung}
~~~~

(assuming that I haven't forgotten the syntax). "Renaming" the embedded file is the main point of the second argument.

**Comment by TeXhackse** [comment]
The file name is correct. That's not what I mean.

`l3pdffile` is using ` l3ef0001`, … for the array containing the files. It seems to not be part of the standard (at least as far as I could see until now), but some viewers or other software claiming to support that format, like e.g. the Quba viewer (https://quba-viewer.org/) is using that name to detect the invoicing xml. 

I was wondering if you see any issues which might be created if I would like to support that. This is of course an internal name and I didn't want to temporary overwrite the internal command.

**Comment by u-fischer** [comment]
Ah. Not you don't need to (mis)use internals for this. There is a second access to EmbeddedFiles that allows you to set a dedicated string:

~~~~
\pdffile_embed_file:nnn {\g__zugferd_xml_file_tl}{xrechnung.xml}{zugferd/rechnung}
\pdfmanagement_add:nne
  {Catalog/Names/EmbeddedFiles}
  {xrechnung.xml}
  {\pdf_object_ref:n{zugferd/rechnung}}
~~~~

(The value should be a simple string that can be sorted alphabetically with `\seq_sort:Nn`.)

**Comment by TeXhackse** [comment]
Thanks a lot. I added that yesterday and you are right, it resolves all the issues I faced with that. 

Will try to publish a release containing this today.
