### ISSUE TITLE
Adding additional entries into XML

### ISSUE THREAD

**Issue by t-b** [TeXhackse/LaTeX-ZUGFeRD#27]
The buyer party gave me an order ID and seller ID. Now I would like to enter that into the XML. From my understanding this is currently not possible or?

See e.g. [1] for how DB wants it.

I think for now having the ability to add [2] BT-13 (Bestellnummer), BT-29 (Verkäufer Kennung/Kreditorennummer) should be sufficient. Although DB above also suggests to fill in BT-56/58 which kind of makes sense. So I don't know how much effort a more generic solution would be.

[1]: https://lieferanten.deutschebahn.com/resource/blob/8749176/5ac217ac9dc9e497f9b89ddeeb08be9a/Merkblatt-XRechnung-FAQ-Deutsche-Bahn-AG-Stand-13-02-2024--data.pdf
[2]: https://www.e-rechnung-bund.de/wp-content/uploads/2023/03/Uebersichtslisten-Eingabefelder-ZRE.pdf

**Comment by TeXhackse** [comment]
Actually I added BT-29 and BT-13 locally yesterday. The thing taking more time is preparing a public interface and add the documentation. Busy week so it will probably take a few days until I publish that part.

**Comment by TeXhackse** [comment]
BT-56/58 where already supported anyway. But this brings me to, maybe I should also add an interface allowing to use the BT numbers instead …  But that's a different story.

**Comment by t-b** [comment]
> BT-56/58 where already supported anyway.

Ah this is seller/[contact, email, phone] right?

> But this brings me to, maybe I should also add an interface allowing to use the BT numbers instead … But that's a different story.

Maybe it's enough to document the mapping between the BT-XXX numbers and the SetZUGFeRDData keys.

> But this brings me to, maybe I should also add an interface allowing to use the BT numbers instead … But that's a different story.

Not sure what is easier to implement
