### ISSUE TITLE
\__zugferd_ApplicableTradeTax:nnnn does not accept macros as second argument

### ISSUE THREAD

**Issue by freswa** [TeXhackse/LaTeX-ZUGFeRD#3]
Thank you for this great package. I was about to write something myself when I came across your work.

Looks pretty good overall, but I have issues with some macros not resolving. I'm not really sure if it is a problem with my code though.

If I use
```
  \__zugferd_ApplicableTradeTax:nnnn{S}{\fp_eval:n {10}}{\fp_eval:n {\int_sinv_invoicetotal / 1000}}{\fp_eval:n {\int_sinv_invoicetax / 1000}}
```
it returns the following xml section:
```
          <ram:ApplicableTradeTax>
            <ram:CalculatedAmount>107.57</ram:CalculatedAmount>
            <ram:TypeCode>VAT</ram:TypeCode>
            <ram:BasisAmount>566.14</ram:BasisAmount>
            <ram:CategoryCode>S</ram:CategoryCode>
            <ram:RateApplicablePercent>\fp_eval:n {10}</ram:RateApplicablePercent>
          </ram:ApplicableTradeTax>
 ```

I wonder why the RateApplicablePercent argument is not resolved here. Do you have any idea?

**Comment by TeXhackse** [comment]
As It accepts an integer there the idea was to use the option to set that value to be able to do some calculation with it.

It's  of course possible to expand the arguments before using it. Usually one would either define a variant expanding it or expand the value before placement. Generally the `\SetZUGFeRDData`macro includes  the mechanism to expand in advance.

**Comment by TeXhackse** [comment]
Oh … and generally you should be aware, that the macro is marked as internal. So please do not use it directly outside the scope of the module.

**Comment by freswa** [comment]
Sorry for the dumb question, but I don't see anything out of the ordinary that looks like a mechanism to expand in advance in this code.
```
\NewDocumentCommand{\SetZUGFeRDData}{sm}{
\IfBooleanTF{#1}{\keys_set:ne}{\keys_set:nn}
{zugferd} {#2}
}
```

> Oh … and generally you should be aware, that the macro is marked as internal. So please do not use it directly outside the scope of the module.

I'm writing my own `zugferd-invoice.sty`, because I need to use a `tabularray` environment for my invoice. I do try to not use any internal code, but it's currently impossible (I know the code is wip). And yes, I know that things can break. No worries :)

**Comment by TeXhackse** [comment]
`\keys_set:ne` is expanding the second argument, while `\keys_set:nn` is not. In case that's not clear please have a look at the expl3 syntax basics, e.g. at https://doi.org/10.47397/tb/44-1/tb136peischl-expl3

The zugferd-invoice is an example package as stated in the README. So developers are intended to write their own variant. You should just not change anything about the behavior or the internals and ensure that you know what you are doing.

I bet you would not have to use tabularray, but I simply would not recommend as there might be issues with increasing table size.  So be aware of that as well as the content will be processed multiple times.

**Comment by freswa** [comment]
Oh, it's too late for me. Overlooked the `ne` definition there. Thanks!
