### ISSUE TITLE
xelatex and lualatex don't interpret ^^c3^^9cberweisung as intended

### ISSUE THREAD

**Issue by knupero** [TeXhackse/LaTeX-ZUGFeRD#30]
With "lualatex DEMO-rechnung-zugferd.tex" and "xelatex DEMO-rechnung-zugferd.tex" latex complains about a missing \begin{document}

This is related to the definition of "Überweisung" as "^^c3^^9cberweisung" in zugferd.sty.

xelatex generates "<ram:Information>Zahlung per SEPA Ã^^9cberweisung.</ram:Information><ram:PayeePartyCreditorFinancialAccount>" in the xml file.

lualatex generates "<ram:Information>Zahlung per SEPA Ãberweisung.</ram:Information><ram:PayeePartyCreditorFinancialAccount>"

pdflatex works fine: "<ram:Information>Zahlung per SEPA Überweisung.</ram:Information><ram:PayeePartyCreditorFinancialAccount>"

**Comment by TeXhackse** [comment]
Sounds like an encoding issue on your side. I also use lualatex.

Would require more information.

**Comment by knupero** [comment]
linux 64-bit, openSuSE tumbleweed. Nothing special about encoding. LANG=de_DE.UTF-8.  

TeX Live, full install, a few hours old. The logfile shows clearly that only files from that installation are used.

 Fresh LaTeX-ZUGFeRD, git 9cf70f3

(pdf|xe|lua)latex DEMO-rechnung-zugferd.tex exposes the problem for lualatex and xelatex.

I also experienced that problem with version 0.8  of LaTeX-ZUGFeRD (2024-09-11) and TeX Live 2024  provided by openSuSE.

What information do you need?

**Comment by TeXhackse** [comment]
As you say it's a definition inside zugferd.sty … I can somehow imagine that this might happen when one is unpacking using some different encoding but UTF-8… sounds confusing. Can you provide a log of the unpacking process?

Sounds a bit like you have multiple binaries and some non-utf8 one somewhere. 
So maybe adding `\listfiles` at the beginning and having a look at the file list might help. Would have a close look at all logs.

**Comment by knupero** [comment]
Yes. Don't use "tex zugferd.ins", stupid ;-) luatex, pdftex and xetex process zugferd.ins as expected.

**Comment by TeXhackse** [comment]
Or even better … make use of the l3build config. The binary to unpack may be configured there. I maintain a bunch of packaged where only one specific one would do it correct.
