### ISSUE TITLE
VAT exemption 

### ISSUE THREAD

**Issue by knupero** [TeXhackse/LaTeX-ZUGFeRD#31]
In "Spezifikation Standard XRechnung" I read:

_13.3. Umgang mit der Steuerbefreiung von Kleinunternehmern
Unter Verwendung des Standards XRechnung können auch Rechnungen von Kleinunterneh-
mern abgebildet werden, bei denen gem. § 19 UStG keine Umsatzsteuer erhoben wird. Dazu
sind folgende Informationselemente wie folgt zu befüllen:
Name ID  Wert
Seller additional legal information    BT-33    „Kein Ausweis von Umsatzsteuer, da Kleinunternehmer gemäß § 19 UStG“
VAT category taxable amount            BT-116    Die Summe aller Beträge (BT-131), die der Kleinunternehmerregelung unterliegen.
VAT category tax amount                BT-117 0
VAT category code                      BT-118 E
VAT category rate                      BT-119 0
VAT exemption reason text              BT-120    „Kein Ausweis von Umsatzsteuer, da Kleinunternehmer gemäß § 19 UStG“
 
„VAT exemption reason code“ (BT-121) wird nicht übermittelt, weil die benötigte Codeliste
von der CEF (Connecting Europe Facility) bisher nicht veröffentlicht wurde._

I would expect that adding something like

`\AddInvoiceItem<unit=one,tax/category={E},tax/exemption-reason={Kein Ausweis von Umsatzsteuer\, da Kleinunternehmer gemäß § 19 UStG}>[0]{3}{IrgendEineWare}{90}`

to DEMO-rechnung-zugferd.tex should give a xml file that contains the given exemption-reason. Unfortunately that's not the case. I also do not see a way to easily add that "Seller additional legal information".

**Comment by TeXhackse** [comment]
There should be a warning informing you that category `E` does not work with the auto-exemption-reason. Is that one missing? 

You can define category E and a corresponding exemption-reason in your `zugferd-invoice.sty`.

It's true that the example implementation in `zugferd-invoice.sty` does (currently – not sure if I should change that) not support adding a reason per Item. The implementation combining the category with the tax rate itself and using the reason attached to the rate. 

I am not sure if I would count it as a standard business case to add multiple different VAT exemption reasons within a single invoice …

**Comment by knupero** [comment]
BTW: I also do not see exemption reason strings/code for other exemption categories. E.g.

`\AddInvoiceItem<unit=one,tax/category={K}>[0]{3}{IrgendEineWare Kategorie K}{90}` 

is compiled to


```
<ram:IncludedSupplyChainTradeLineItem>
<ram:AssociatedDocumentLineDocument>
<ram:LineID>02</ram:LineID>
</ram:AssociatedDocumentLineDocument>
<ram:SpecifiedTradeProduct>
<ram:Name>IrgendEineWare Kategorie K</ram:Name>
</ram:SpecifiedTradeProduct>
<ram:SpecifiedLineTradeAgreement>
<ram:NetPriceProductTradePrice>
<ram:ChargeAmount>90</ram:ChargeAmount>
</ram:NetPriceProductTradePrice>
</ram:SpecifiedLineTradeAgreement>
<ram:SpecifiedLineTradeDelivery>
<ram:BilledQuantity unitCode="C62">3</ram:BilledQuantity>
</ram:SpecifiedLineTradeDelivery>
<ram:SpecifiedLineTradeSettlement>
<ram:ApplicableTradeTax>
<ram:TypeCode>VAT</ram:TypeCode>
<ram:CategoryCode>K</ram:CategoryCode>
<ram:RateApplicablePercent>0</ram:RateApplicablePercent>
</ram:ApplicableTradeTax>
<ram:SpecifiedTradeSettlementLineMonetarySummation>
<ram:LineTotalAmount>270</ram:LineTotalAmount>
</ram:SpecifiedTradeSettlementLineMonetarySummation>
</ram:SpecifiedLineTradeSettlement>
</ram:IncludedSupplyChainTradeLineItem>
```

**Comment by TeXhackse** [comment]
I would not expect the DEMO interface to use it that way, as there is a difference between the entry at the item and the summation. There one has to ensure the value matches at the moment the summation is printed. But thanks for providing more details,

I will have a look at it.

**Comment by knupero** [comment]
Let me summarize what I learned from reading the code up to now:

The documentation claims that you can specify various parameters regarding tax exemption per item. This suggests that the following would be correct: 

`\AddInvoiceItem<unit=one,tax/category={E},tax/exemption-reason={valid reason}>[0]{1}{what we sold}{60}
`

If \InitVAT{0}[E] in zugferd-invoice.sty enables the use of a tax rate of 0, *latex also accepts this, and if you then specify an exemption reason (and an exemption reason) for tax/category{E} in zugferd.sty, then you could assume that a correct invoice would be created due to the lack of warnings from *lualatex.

However, tax/exemption-reason strings given in \AddInvoiceItem are ignored and do not appear in the xml. This is a bug.

Furthermore, the tax rate 0 is ignored in \PrintInvoiceTotal (due to \fp_compare:nNnF {\fp_use:c {g__ptxcd_invoice_sum_vat##1_fp}} = {0} {...}) and therefore a  “VAT breakdown” is also missing in the xml. Reading 
"Spezifikation Standard XRechnung / CIUS und Extension / Version XRechnung 3.0.2" chapter 11.33 and chapter 13.3 I believe that such a tax breakdown is also necessary for tax rate zero.

If you remove this limitation in \PrintInvoiceTotal, a VAT breakdown appears in the xml. The category used here for sales with a certain tax rate is defined in zugferd-invoice.sty with InitVAT, it has nothing to do with the tax/category given in \AddInvoiceItem.

Furthermore, when writing the tax breakdown in the xml in zugferd.sty, the assignment of the exemtion reason to the category is incorrect. Something like this would probably be correct in \__zugferd_define_xml_writer:Nn \__zugferd_ApplicableTradeTax:nnnn:


```
\keys_set:nx { zugferd/tax } {exemption-reason-auto={#1}}
\tl_if_blank:VF \l__zugferd_tax_exemption_reason_tl {%BT-120
\__zugferd_write_xml:e {<ram:ExemptionReason>\tl_use:N \l__zugferd_tax_exemption_reason_tl</ram:ExemptionReason>}

```
not that code

```
\tl_if_blank:VF \l__zugferd_tax_exemption_reason_tl {%BT-120
\__zugferd_write_xml:e {<ram:ExemptionReason>\l__zugferd_tax_exemption_reason_tl</ram:ExemptionReason>}
}
```

If you change the code as given and also add the BT-33 code I published here yesterday, then in simple case of exactly one execemption reason used in an invoice you create what I think is a correct xml. For someone who only wants to display invoices with exemption according to §19 USTG, this is enough.

However, after doing that there is still the limitation that latex-zugferd is not able to generate more than one correct tax breakdown for the tax rate 0 percent without more than trivial additional code. You would have to support several InitVATs for the same tax rate with different categories, map invoice items accordingly and even that would not be sufficient for someone who can claim different exemption reasons in category E to show sales with two different exemption reasons according to category E in one invoice.

**Comment by TeXhackse** [comment]
Please move separate topic to sepate issues. I move the legalinfo thing.

On the exemption reason: the `eea.lvt` testfile is constructed to check this. The exemption reason is added when the info on the VAT is printed. that's why it's not working if you add it locally to an item. But… this is two different things. You can add it to a VAT rate instead. It's therefore still possible to edit it for an item itself, technically, but this means you have to build two different summations. This is something which the interfaces of zugferd support, but the zugferd-invoice.sty package does not, as I don't thing this is a thing the most people would need. For all businesscases I saw so far it's enough to have one reason. 

This differs e.g. if you have export items as well as services. But I guess this does not apply for most of us.

**Comment by knupero** [comment]
After reading zugferd.pdf, I foolishly assumed that DEMO-rechnung-zugferd.tex should also be able to correctly process sales with tax exemptions. Incorrect assumptions about the intended function of the code then led to misguided repair requests.

Starting from eea.lvt, it was surprisingly easy to add the xrechnung functionality to my old code. Thank you for your work and patience!

**Comment by clwe** [comment]
After reading through this thread I still don't know how to make an invoice with VAT exemption for "Kleinunternehmer". Can you point me to an example? Very much appreciated, thank you!

**Comment by TeXhackse** [comment]
Theres a test file corresponding to that + i added an extra example file based on the current status within the dev branch.

**Comment by clwe** [comment]
Thank you! 
For those who are not so latex or git savvy:
open a shell and then:
```
git clone https://github.com/TeXhackse/LaTeX-ZUGFeRD.git
cd LaTeX-ZUGFeRD 
git checkout develop
l3build install
l3build doc
```
This should install the new latex packkage and build the examples.
