### ISSUE TITLE
for 5-digit numbers a space is inserted after the thousands digit, but not for 4-digit numbers

### ISSUE THREAD

**Issue by spi43984** [TeXhackse/LaTeX-ZUGFeRD#41]
For 5-digit numbers a space is inserted after the thousands digit, but not for 4-digit numbers.

![image](https://github.com/user-attachments/assets/92390a26-9a49-4ec0-a56c-7a28947cbb57)

![image](https://github.com/user-attachments/assets/1305f1c6-89d4-4b8d-95fa-51123b42796b)

Is there a simple way to fix that? Or can one use a dot as a thousands separator?

**Comment by TeXhackse** [comment]
You can. Have a look at the siunitx documentation or use your own tabular mechanism to render the numbers.

**Comment by spi43984** [comment]
Thx, found that.
That seems to be the default setting `\sisetup{group-digits=integer,group-minimum-digits=5}`.
Adding `\sisetup{group-digits=integer,group-minimum-digits=4}` to the invoice.tex adds a space to 4-digit numbers as well.
`\sisetup{group-digits=integer, group-separator={.},group-minimum-digits=4,digit-group-size=3}` instead gives a dot as separator.

**Comment by TeXhackse** [comment]
It's configureable. that's the important part. You don't need to use this at all. As I said it's a demo implementation.  You generall< don't want to hardcode the group-separator in case your invoicing should support multiple languages. So be careful with these.
