### ISSUE TITLE
use of internal l3pdfmeta commands ...

### ISSUE THREAD

**Issue by u-fischer** [TeXhackse/LaTeX-ZUGFeRD#7]
I just sent a new version of the pdfmanagement to ctan which contains public version of `\__pdfmeta_xmp_schema_new:nnn` and `\__pdfmeta_xmp_property_new:nnnnn` which you can use instead of the internals. Note: you do not need a variant `:nne` of the first, the hash in the uri is expanded anyway. 

The example in the pdfresources has been updated.

**Comment by TeXhackse** [comment]
Thanks - actually I was expecting you to do something like this at some point. But wanted to finish the “other thing” (you know what I mean ;-) ) first, before I ask when this would happen. 

I will change this afterwards.

**Comment by TeXhackse** [comment]
@u-fischer thanks again, I just resolved this and will prepare a small patch release today. And … I now tried to pay more attention on that within the koma-tagging thing.
